"""Init3

Revision ID: 09fc53511502
Revises: 357b5542c07f
Create Date: 2023-10-29 23:57:26.019734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09fc53511502'
down_revision: Union[str, None] = '357b5542c07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('hall', sa.Integer(), nullable=False))
    op.drop_constraint('show_hall_id_fkey', 'show', type_='foreignkey')
    op.drop_column('show', 'hall_id')
    op.drop_table('hall')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('hall_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('show_hall_id_fkey', 'show', 'hall', ['hall_id'], ['id'])
    op.drop_column('show', 'hall')
    op.create_table('hall',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hall_num', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hall_pkey')
    )
    # ### end Alembic commands ###
